-- OG_SYS_DEPT definition

CREATE TABLE "OG_SYS_DEPT" 
   ("DEPT_ID" NUMBER(19,0) NOT NULL , 
	"PARENT_ID" NUMBER(19,0), 
	"DEPT_NAME" VARCHAR2(50) NOT NULL , 
	"SHOW_ORDER" NUMBER(10,0) NOT NULL , 
	"CREATE_USER_ID" NUMBER(19,0) NOT NULL , 
	"CREATE_TIME" TIMESTAMP (6) NOT NULL , 
	"UPDATE_USER_ID" NUMBER(19,0) NOT NULL , 
	"UPDATE_TIME" TIMESTAMP (6) NOT NULL , 
	"DELETED_FLAG" NUMBER(10,0) NOT NULL , 
	"DEPT_CODE" VARCHAR2(20), 
	 CONSTRAINT "PK_DEPT_ID" PRIMARY KEY ("DEPT_ID") 
   );

CREATE UNIQUE INDEX "PK_DEPT_ID" ON "OG_SYS_DEPT" ("DEPT_ID");
CREATE INDEX "IDX_DEPT_PARENT_ID" ON "OG_SYS_DEPT" ("PARENT_ID");
CREATE INDEX "IDX_DEPT_SHOW_ORDER" ON "OG_SYS_DEPT" ("SHOW_ORDER");

COMMENT ON TABLE OG_SYS_DEPT IS '部门管理表';
COMMENT ON COLUMN OG_SYS_DEPT.DEPT_ID IS '部门Id';
COMMENT ON COLUMN OG_SYS_DEPT.PARENT_ID IS '父部门Id';
COMMENT ON COLUMN OG_SYS_DEPT.DEPT_NAME IS '部门名称';
COMMENT ON COLUMN OG_SYS_DEPT.SHOW_ORDER IS '兄弟部分之间的显示顺序，数字越小越靠前';
COMMENT ON COLUMN OG_SYS_DEPT.CREATE_USER_ID IS '创建者Id';
COMMENT ON COLUMN OG_SYS_DEPT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN OG_SYS_DEPT.UPDATE_USER_ID IS '更新者Id';
COMMENT ON COLUMN OG_SYS_DEPT.UPDATE_TIME IS '最后更新时间';
COMMENT ON COLUMN OG_SYS_DEPT.DELETED_FLAG IS '删除标记(1: 正常 -1: 已删除)';


-- OG_SYS_DEPT_POST definition

CREATE TABLE "OG_SYS_DEPT_POST" 
   ("DEPT_POST_ID" NUMBER(19,0) NOT NULL , 
	"DEPT_ID" NUMBER(19,0) NOT NULL , 
	"POST_ID" NUMBER(19,0) NOT NULL , 
	"POST_SHOW_NAME" VARCHAR2(255) NOT NULL , 
	 CONSTRAINT "PK_DEPT_POST_ID" PRIMARY KEY ("DEPT_POST_ID")
   );

CREATE UNIQUE INDEX "PK_DEPT_POST_ID" ON "OG_SYS_DEPT_POST" ("DEPT_POST_ID");
CREATE INDEX "IDX_DEPT_POST_DEPT_ID" ON "OG_SYS_DEPT_POST" ("DEPT_ID");
CREATE INDEX "IDX_DEPT_POST_POST_ID" ON "OG_SYS_DEPT_POST" ("POST_ID");

COMMENT ON COLUMN OG_SYS_DEPT_POST.DEPT_POST_ID IS '主键Id';
COMMENT ON COLUMN OG_SYS_DEPT_POST.DEPT_ID IS '部门Id';
COMMENT ON COLUMN OG_SYS_DEPT_POST.POST_ID IS '岗位Id';
COMMENT ON COLUMN OG_SYS_DEPT_POST.POST_SHOW_NAME IS '部门岗位显示名称';


-- OG_SYS_DEPT_RELATION definition

CREATE TABLE "OG_SYS_DEPT_RELATION" 
   (	"PARENT_DEPT_ID" NUMBER(19,0) NOT NULL , 
	"DEPT_ID" NUMBER(19,0) NOT NULL , 
	 CONSTRAINT "PK_PARENT_DEPT_ID_DEPT_ID" PRIMARY KEY ("PARENT_DEPT_ID", "DEPT_ID") 
   );

CREATE UNIQUE INDEX "PK_PARENT_DEPT_ID_DEPT_ID" ON "OG_SYS_DEPT_RELATION" ("PARENT_DEPT_ID", "DEPT_ID");
  CREATE INDEX "IDX_DEPT_RELATION_DEPT_ID" ON "OG_SYS_DEPT_RELATION" ("DEPT_ID");

COMMENT ON TABLE OG_SYS_DEPT_RELATION IS '部门关联关系表';
COMMENT ON COLUMN OG_SYS_DEPT_RELATION.PARENT_DEPT_ID IS '父部门Id';
COMMENT ON COLUMN OG_SYS_DEPT_RELATION.DEPT_ID IS '部门Id';


-- OG_SYS_POST definition

CREATE TABLE "OG_SYS_POST" 
   (	"POST_ID" NUMBER(19,0) NOT NULL , 
	"POST_NAME" VARCHAR2(255) NOT NULL , 
	"POST_LEVEL" NUMBER(10,0) NOT NULL , 
	"LEADER_POST" NUMBER(10,0) DEFAULT 0 NOT NULL , 
	"CREATE_USER_ID" NUMBER(19,0) NOT NULL , 
	"CREATE_TIME" TIMESTAMP (6) NOT NULL , 
	"UPDATE_USER_ID" NUMBER(19,0) NOT NULL , 
	"UPDATE_TIME" TIMESTAMP (6) NOT NULL , 
	"DELETED_FLAG" NUMBER(10,0) NOT NULL , 
	 CONSTRAINT "PK_POST_ID" PRIMARY KEY ("POST_ID") 
   );

CREATE UNIQUE INDEX "PK_POST_ID" ON "OG_SYS_POST" ("POST_ID");

COMMENT ON COLUMN OG_SYS_POST.POST_ID IS '岗位Id';
COMMENT ON COLUMN OG_SYS_POST.POST_NAME IS '岗位名称';
COMMENT ON COLUMN OG_SYS_POST.POST_LEVEL IS '岗位层级，数值越小级别越高';
COMMENT ON COLUMN OG_SYS_POST.LEADER_POST IS '是否领导岗位';
COMMENT ON COLUMN OG_SYS_POST.CREATE_USER_ID IS '创建者Id';
COMMENT ON COLUMN OG_SYS_POST.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN OG_SYS_POST.UPDATE_USER_ID IS '更新者Id';
COMMENT ON COLUMN OG_SYS_POST.UPDATE_TIME IS '最后更新时间';
COMMENT ON COLUMN OG_SYS_POST.DELETED_FLAG IS '逻辑删除标记(0: 正常 1: 已删除)';


-- OG_SYS_USER definition

CREATE TABLE "OG_SYS_USER" 
   (	"USER_ID" NUMBER(19,0) NOT NULL , 
	"LOGIN_NAME" VARCHAR2(64) NOT NULL , 
	"PASSWORD" VARCHAR2(64) NOT NULL , 
	"SHOW_NAME" VARCHAR2(32) NOT NULL , 
	"DEPT_ID" NUMBER(19,0) NOT NULL , 
	"HEAD_IMAGE_URL" VARCHAR2(512), 
	"USER_TYPE" NUMBER(10,0) NOT NULL , 
	"WORK_CODE" VARCHAR2(50), 
	"MANAGER_ID" NUMBER(19,0), 
	"PHONE" VARCHAR2(50), 
	"NAME_EN" VARCHAR2(50), 
	"EMAIL" VARCHAR2(100), 
	"USER_STATUS" NUMBER(10,0) NOT NULL , 
	"CREATE_USER_ID" NUMBER(19,0) NOT NULL , 
	"CREATE_TIME" TIMESTAMP (6) NOT NULL , 
	"UPDATE_USER_ID" NUMBER(19,0) NOT NULL , 
	"UPDATE_TIME" TIMESTAMP (6) NOT NULL , 
	"DELETED_FLAG" NUMBER(10,0) NOT NULL , 
	 CONSTRAINT "PK_USER_ID" PRIMARY KEY ("USER_ID")
   );

CREATE UNIQUE INDEX "PK_USER_ID" ON "OG_SYS_USER" ("USER_ID");
  CREATE INDEX "IDX_USER_DEPT_ID" ON "OG_SYS_USER" ("DEPT_ID");
  CREATE UNIQUE INDEX "UK_USER_LOGIN_NAME" ON "OG_SYS_USER" ("LOGIN_NAME");
  CREATE INDEX "IDX_USER_USER_STATUS" ON "OG_SYS_USER" ("USER_STATUS");

COMMENT ON TABLE OG_SYS_USER IS '系统用户表';
COMMENT ON COLUMN OG_SYS_USER.USER_ID IS '主键Id';
COMMENT ON COLUMN OG_SYS_USER.LOGIN_NAME IS '用户登录名称';
COMMENT ON COLUMN OG_SYS_USER.PASSWORD IS '密码';
COMMENT ON COLUMN OG_SYS_USER.SHOW_NAME IS '用户显示名称';
COMMENT ON COLUMN OG_SYS_USER.DEPT_ID IS '用户所在部门Id';
COMMENT ON COLUMN OG_SYS_USER.HEAD_IMAGE_URL IS '用户头像的Url';
COMMENT ON COLUMN OG_SYS_USER.USER_TYPE IS '用户类型(0: 管理员 1: 系统管理用户 2: 系统业务用户)';
COMMENT ON COLUMN OG_SYS_USER.WORK_CODE IS '工号';
COMMENT ON COLUMN OG_SYS_USER.MANAGER_ID IS '直接上级';
COMMENT ON COLUMN OG_SYS_USER.PHONE IS '电话';
COMMENT ON COLUMN OG_SYS_USER.NAME_EN IS '英文名';
COMMENT ON COLUMN OG_SYS_USER.EMAIL IS 'E-mail';
COMMENT ON COLUMN OG_SYS_USER.USER_STATUS IS '状态(0: 正常 1: 锁定)';
COMMENT ON COLUMN OG_SYS_USER.CREATE_USER_ID IS '创建者Id';
COMMENT ON COLUMN OG_SYS_USER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN OG_SYS_USER.UPDATE_USER_ID IS '更新者Id';
COMMENT ON COLUMN OG_SYS_USER.UPDATE_TIME IS '最后更新时间';
COMMENT ON COLUMN OG_SYS_USER.DELETED_FLAG IS '删除标记(1: 正常 -1: 已删除)';


-- OG_SYS_USER_POST definition

CREATE TABLE "OG_SYS_USER_POST" 
   (	"USER_ID" NUMBER(19,0) NOT NULL , 
	"DEPT_POST_ID" NUMBER(19,0) NOT NULL , 
	"POST_ID" NUMBER(19,0) NOT NULL , 
	 CONSTRAINT "PK_USER_ID_DEPT_POST_ID" PRIMARY KEY ("USER_ID", "DEPT_POST_ID")
   ) ;

CREATE UNIQUE INDEX "PK_USER_ID_DEPT_POST_ID" ON "OG_SYS_USER_POST" ("USER_ID", "DEPT_POST_ID");
  CREATE INDEX "IDX_USER_POST_POST_ID" ON "OG_SYS_USER_POST" ("POST_ID") ;

COMMENT ON COLUMN OG_SYS_USER_POST.USER_ID IS '用户Id';
COMMENT ON COLUMN OG_SYS_USER_POST.DEPT_POST_ID IS '部门岗位Id';
COMMENT ON COLUMN OG_SYS_USER_POST.POST_ID IS '岗位Id';




INSERT INTO og_sys_dept VALUES(1507731603810422786,NULL,'公司总部',1,1507731603751702528,sysdate,1507731603751702528,sysdate,0,0);
INSERT INTO og_sys_user VALUES(1507731603751702528,'admin','$2a$10$498XIgU9OTnwli1mxlNV3u3gbg2FjeRJHec3d7fK0xmdv.o8TlKRG','管理员',1507731603810422786,NULL,0,0,1507731603751702528,sysdate,1507731603751702528,sysdate,0,0,sysdate,0,sysdate,0);
INSERT INTO og_sys_dept_relation VALUES(1507731603810422786,1507731603810422786);