
-- ----------------------------
-- Table structure for OG_LOT_OWNER_CHANGE_DETAIL
-- ----------------------------
DROP TABLE "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL";
CREATE TABLE "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "MAIN_ID" NUMBER(19,0) VISIBLE,
  "LOT_ID" VARCHAR2(50 BYTE) VISIBLE,
  "FOUP_ID" VARCHAR2(50 BYTE) VISIBLE,
  "PRODUCT_ID" VARCHAR2(50 BYTE) VISIBLE,
  "LOT_OWNER" NUMBER(19,0) VISIBLE,
  "PRIORITY" VARCHAR2(50 BYTE) VISIBLE,
  "QTY" NUMBER(19,0) VISIBLE DEFAULT NULL,
  "STAGE_NAME" VARCHAR2(255 BYTE) VISIBLE,
  "STEP_DESC" VARCHAR2(255 BYTE) VISIBLE,
  "STEP_SEQ" VARCHAR2(255 BYTE) VISIBLE,
  "LOT_STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "HOLD_OWNER" VARCHAR2(50 BYTE) VISIBLE,
  "HOLD_CODE" VARCHAR2(50 BYTE) VISIBLE,
  "HOLD_DESC" VARCHAR2(255 BYTE) VISIBLE,
  "HOLD_COMMENT" VARCHAR2(255 BYTE) VISIBLE,
  "CREATE_TIME" DATE VISIBLE,
  "CREATE_USER_ID" NUMBER(19,0) VISIBLE DEFAULT NULL,
  "UPDATE_TIME" DATE VISIBLE,
  "UPDATE_USER_ID" NUMBER(19,0) VISIBLE DEFAULT NULL,
  "DELETED_FLAG" NUMBER(1,0) VISIBLE DEFAULT 0 NOT NULL,
  "LOT_TYPE" VARCHAR2(50 BYTE) VISIBLE
)
;
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL"."MAIN_ID" IS '主表ID';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL"."LOT_ID" IS 'LOT ID';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL"."FOUP_ID" IS 'FOUP ID';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL"."PRODUCT_ID" IS 'PRODUCT ID';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL"."LOT_OWNER" IS 'LOT OWNER ID';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL"."PRIORITY" IS 'PRIORITY';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL"."QTY" IS 'QTY';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL"."STAGE_NAME" IS 'STAGE NAME';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL"."STEP_DESC" IS 'STEP DESC';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL"."STEP_SEQ" IS 'STEP SEQ';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL"."LOT_STATUS" IS 'LOT 的状态';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL"."HOLD_OWNER" IS 'HOLD_OWNER';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL"."HOLD_CODE" IS 'HOLD_CODE';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL"."HOLD_DESC" IS 'HOLD_DESC';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL"."HOLD_COMMENT" IS 'HOLD_COMMENT';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL"."CREATE_USER_ID" IS '创建人ID';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL"."UPDATE_USER_ID" IS '更新人ID';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL"."DELETED_FLAG" IS '0 未删除 1 已删除';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL"."LOT_TYPE" IS 'LOT_TYPE';
 
-- ----------------------------
-- Primary Key structure for table OG_LOT_OWNER_CHANGE_DETAIL
-- ----------------------------
ALTER TABLE "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE_DETAIL" ADD  PRIMARY KEY ("ID");
 