 
-- ----------------------------
-- Table structure for OG_LOT_OWNER_CHANGE
-- ----------------------------
DROP TABLE "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE";
CREATE TABLE "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE" (
"ID" NUMBER(19) NOT NULL ,
"FLOW_NUMBER" VARCHAR2(25 BYTE) NULL ,
"APPLICANT_ID" VARCHAR2(50 BYTE) NULL ,
"APPLICANT_WORK_CODE" VARCHAR2(50 BYTE) NULL ,
"APPLICANT_NAME_ZH" VARCHAR2(50 BYTE) NULL ,
"APPLICANT_NAME_US" VARCHAR2(50 BYTE) NULL ,
"APPLICANT_DEPT" VARCHAR2(50 BYTE) NULL ,
"TYPE_FROM" VARCHAR2(50 BYTE) NULL ,
"TYPE_TO" VARCHAR2(50 BYTE) NULL ,
"REASON_DESCRIPTION" VARCHAR2(1000 BYTE) NULL ,
"STATUS" VARCHAR2(50 BYTE) NULL ,
"CREATE_TIME" DATE NULL ,
"CREATE_USER_ID" NUMBER(19) DEFAULT NULL  NULL ,
"UPDATE_TIME" DATE NULL ,
"UPDATE_USER_ID" NUMBER(19) DEFAULT NULL  NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NOT NULL ,
"ATTACHMENT" VARCHAR2(3500 BYTE) NULL ,
"SWITCH_PRO_TO_OTHER" CHAR(1 BYTE) NULL ,
"TEL" VARCHAR2(50 BYTE) NULL 
) 

;
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE"."FLOW_NUMBER" IS '流程单号';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE"."APPLICANT_ID" IS '申请人ID';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE"."APPLICANT_WORK_CODE" IS '申请人工号';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE"."APPLICANT_NAME_ZH" IS '申请人中文名';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE"."APPLICANT_NAME_US" IS '申请人英文名';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE"."APPLICANT_DEPT" IS '申请人部门';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE"."TYPE_FROM" IS '带出来的类型';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE"."TYPE_TO" IS '想要修改成什么类型';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE"."REASON_DESCRIPTION" IS '修改原因';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE"."STATUS" IS '流程状态';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE"."CREATE_USER_ID" IS '创建人ID';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE"."UPDATE_USER_ID" IS '更新人ID';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE"."DELETED_FLAG" IS '0 未删除 1 已删除 ';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE"."ATTACHMENT" IS '文件';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE"."SWITCH_PRO_TO_OTHER" IS '是否将产品切换为其他  0 否 1 是';
COMMENT ON COLUMN "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE"."TEL" IS '电话号码';
 
-- ----------------------------
-- Primary Key structure for table OG_LOT_OWNER_CHANGE
-- ----------------------------
ALTER TABLE "LOT_OWNER_CHANGE"."OG_LOT_OWNER_CHANGE" ADD PRIMARY KEY ("ID");
